esp32:
  variant: esp32c3
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: -10
    then:
      - output.turn_on: ant_gpio2  # HIGH → external antenna

logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: USB_CDC

api:
  encryption:
    key: ${api_key}
  reboot_timeout: 15min

 ota:
  - platform: esphome
    password: ${ota_password}
    version: 2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local
  use_address: ${device_name}.local
  power_save_mode: NONE
  fast_connect: true
  enable_on_boot: true
  reboot_timeout: 10min
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_captive
    ap_timeout: 120s

captive_portal:

mdns:

# Status LED (C3 uses GPIO10, inverted)
status_led:
  pin:
    number: GPIO10
    inverted: true

# External antenna control
output:
  - platform: gpio
    pin: GPIO2
    id: ant_gpio2

# BLE scanning and Bluetooth proxy for Home Assistant
esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 211ms
    window: 180ms
    continuous: true

bluetooth_proxy:
  active: true

# Text sensors for Wi-Fi info
text_sensor:
  - platform: wifi_info
    bssid:
      name: "BSSID"
      entity_category: diagnostic
    ip_address:
      name: "IP"
      entity_category: diagnostic

# Switches
switch:
  - platform: template
    name: "External Antenna"
    optimistic: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      - output.turn_on: ant_gpio2   # HIGH → external antenna
    turn_off_action:
      - output.turn_off: ant_gpio2  # LOW → internal antenna

# Diagnostics and basics
sensor:
  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "h"
    accuracy_decimals: 2
    update_interval: 60s
    filters:
      - lambda: return x / 3600.0;

  - platform: internal_temperature
    name: "Internal Temp"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "Wi-Fi Signal"
    update_interval: 30s
    entity_category: diagnostic

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
