esp32:
  variant: esp32s3
  board: seeed_xiao_esp32s3
  framework:
    type: esp-idf

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG

api:
  encryption:
    key: ${api_key}
  reboot_timeout: 15min

ota:
  - platform: esphome
    password: ${ota_password}
    version: 2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local
  use_address: ${device_name}.local
  power_save_mode: NONE
  fast_connect: true
  enable_on_boot: true
  reboot_timeout: 10min
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_captive
    ap_timeout: 120s
  on_disconnect:
    then:
      - lambda: |-
          id(_wifi_disconnects_since_boot)++;

captive_portal:

mdns:

# Status LED on Seeed XIAO ESP32-S3 (GPIO21, user LED - active LOW)
status_led:
  pin:
    number: GPIO21

# ===== BLE & Bluetooth Proxy =====
# Default Medium (28% duty cycle); user selection persists across reboots
esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    active: true
    interval: 320ms
    window: 90ms
    continuous: true

bluetooth_proxy:
  active: true

# BLE Scan Profile selector: Low, Medium, High
select:
  - platform: template
    name: "BLE Scan Profile"
    id: sel_ble_scan_profile
    optimistic: true
    restore_value: true
    initial_option: "Medium"
    options:
      - "Low"
      - "Medium"
      - "High"
    set_action:
      - lambda: |-
          id(ble_tracker).stop_scan();
          auto opt = id(sel_ble_scan_profile).current_option();
          if (opt == "Low") {
              id(ble_tracker).set_scan_interval(320);
              id(ble_tracker).set_scan_window(30);
          } else if (opt == "Medium") {
              id(ble_tracker).set_scan_interval(320);
              id(ble_tracker).set_scan_window(90);
          } else {
              id(ble_tracker).set_scan_interval(320);
              id(ble_tracker).set_scan_window(160);
          }
          id(ble_tracker).start_scan();

# Text sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      entity_category: diagnostic
    mac_address:
      name: "MAC"
      entity_category: diagnostic
    ssid:
      name: "SSID"
      entity_category: diagnostic
    bssid:
      name: "BSSID"
      entity_category: diagnostic

# Buttons
button:
  - platform: restart
    name: "Restart Device"

# Basics + Wi-Fi disconnect count (since boot)
sensor:
  - platform: internal_temperature
    name: "Internal Temp"
    entity_category: diagnostic

  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "h"
    accuracy_decimals: 2
    update_interval: 60s
    filters:
      - lambda: return x / 3600.0;
    entity_category: diagnostic

  - platform: wifi_signal
    id: wifi_signal_dbm
    name: "Wi-Fi RSSI"
    update_interval: 30s
    entity_category: diagnostic

  - platform: template
    name: "Wi-Fi Disconnects (since boot)"
    id: wifi_disconnects_since_boot_sensor
    entity_category: diagnostic
    accuracy_decimals: 0
    update_interval: 30s
    lambda: |-
      return id(_wifi_disconnects_since_boot);

# Globals (since-boot only; not restored)
globals:
  - id: _wifi_disconnects_since_boot
    type: int
    restore_value: no
    initial_value: '0'

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
