---
name: Linting

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. YAML Lint
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: "."
          config_data: |
            extends: default
            rules:
              line-length: disable
              truthy:
                allowed-values: ["true", "false", "on"]
              document-start: disable
              comments:
                min-spaces-from-content: 2

      # 2. Markdown Lint
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: "**/*.md"
          fix: true
